spring.application.name=auth-service
server.port=8080
#spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: for JPA
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# todo - remove this update because it will cause problem in production, should be none and flyway should be used for db migrations.
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=hospital-proxy-sync
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
logging.level.root=info
