server:
  port: 8080

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api/patients,/api/patients/**,/api/hospitals,/api/hospitals/**
          filters:
            - StripPrefix=1
          ## filters are used to modify the request before forwarding it to the destination service.
          ## Here, strip-prefix=1 removes the first segment of the path (i.e., "api") before forwarding the request to the patient-service.
        - id: auth-service-route
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
      #########################################################
      #  GLOBAL CORS CONFIGURATION
      #########################################################
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':                                 # Apply these rules to all paths (/**)
            allowedOriginPatterns:                 # Frontend origins that can call this API
              - "http://localhost"
              - "http://localhost:*"
              - "http://127.0.0.1"
              - "http://127.0.0.1:*"
              - "https://*.meditrack.com"
            allowedMethods:                        # HTTP methods allowed from frontend
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: ["*"]                  # Allow any request header from frontend (e.g., Authorization, Content-Type)
            exposedHeaders:                        # Headers that JS in frontend is allowed to read from the response, note what you see in inspect != what JS can access
              - "Authorization"                    # e.g., if you send back a refreshed token
              - "Location"
              - "X-Correlation-Id"                 # e.g., for request tracing/logging in UI
            allowCredentials: true                 # Allow sending cookies or Authorization headers in CORS requests
            maxAge: 3600                           # Cache preflight (OPTIONS) response for 1 hour in the browser
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_UNIQUE
        # Removes duplicate 'Access-Control-Allow-*' headers that can appear
        # when multiple filters or layers add the same header.
