package com.meditrack.patientservice.grpc;

import billing.BillingRequest;
import billing.BillingResponse;
import billing.BillingServiceGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Metadata;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import io.grpc.stub.MetadataUtils;

import static net.logstash.logback.argument.StructuredArguments.kv;

@Slf4j
@Service
public class BillingServiceGrpcClient {
    private static final String TRACE_ID_HEADER = "x-trace-id";
    private static final String TRACE_ID_MDC_KEY = "traceId";
    private static final Metadata.Key<String> TRACE_ID_METADATA_KEY =
            Metadata.Key.of(TRACE_ID_HEADER, Metadata.ASCII_STRING_MARSHALLER);

    //BillingServiceBlockingStub is generated by grpc framework when we compile the proto file, its present inside the BillingServiceGrpc class
    //its a nested class that allows to send Synchonous requests to the server and get responses
    private final BillingServiceGrpc.BillingServiceBlockingStub blockingStub;

    //development - localhost:9002/BillingService/CreateBillingAccount
    //aws - aws-grpc:9002/BillingService/CreateBillingAccount
    //so we will externalize the server address and port using application properties or env. variable of docker image.
    public BillingServiceGrpcClient(
            @Value("${billing.service.address:localhost}") String serverAddress,
            @Value("${billing.service.grpc.port:9002}") int serverPort
    ) {
        log.info(
                "Connecting to billing gRPC service",
                kv("downstream.service.name", "billing-service"),
                kv("rpc.system", "grpc"),
                kv("server.address", serverAddress),
                kv("server.port", serverPort)
        );
        ManagedChannel channel = ManagedChannelBuilder.forAddress(serverAddress, serverPort).usePlaintext().build();
        blockingStub = BillingServiceGrpc.newBlockingStub(channel);
        //now once we have created blockingStub we can use it to make grpc calls to the BillingService grpc server
    }

    public BillingResponse createBillingAccount(String patientId,String name, String email) {
        log.info(
                "Creating billing account through gRPC",
                kv("patient.id", patientId),
                kv("downstream.service.name", "billing-service"),
                kv("rpc.system", "grpc"),
                kv("rpc.method", "CreateBillingAccount")
        );
        //build the request
        BillingRequest request = BillingRequest.newBuilder()
                .setPatientId(patientId).setName(name).setEmail(email).build();
        //make the grpc call using blockingStub
        BillingResponse response = stubWithTraceId().createBillingAccount(request);
        log.info(
                "Received billing account creation response",
                kv("patient.id", patientId),
                kv("billing.account.id", response.getAccountId()),
                kv("rpc.system", "grpc"),
                kv("rpc.method", "CreateBillingAccount"),
                kv("rpc.grpc.status_code", response.getStatus())
        );
        return response;
    }

    private BillingServiceGrpc.BillingServiceBlockingStub stubWithTraceId() {
        String traceId = MDC.get(TRACE_ID_MDC_KEY);
        if (traceId == null || traceId.isBlank()) {
            return blockingStub;
        }

        Metadata metadata = new Metadata();
        metadata.put(TRACE_ID_METADATA_KEY, traceId);
        return blockingStub.withInterceptors(MetadataUtils.newAttachHeadersInterceptor(metadata));
    }
}
