package com.meditrack.patientservice.grpc;

import billing.BillingRequest;
import billing.BillingResponse;
import billing.BillingServiceGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Slf4j
@Service
public class BillingServiceGrpcClient {
    //BillingServiceBlockingStub is generated by grpc framework when we compile the proto file, its present inside the BillingServiceGrpc class
    //its a nested class that allows to send Synchonous requests to the server and get responses
    private final BillingServiceGrpc.BillingServiceBlockingStub blockingStub;

    //development - localhost:9002/BillingService/CreateBillingAccount
    //aws - aws-grpc:9002/BillingService/CreateBillingAccount
    //so we will externalize the server address and port using application properties or env. variable of docker image.
    public BillingServiceGrpcClient(
            @Value("${billing.service.address:localhost}") String serverAddress,
            @Value("${billing.service.grpc.port:9002}") int serverPort
    ) {
        log.info("Connecting to Billing Service Grpc server at {}:{}", serverAddress, serverPort);
        ManagedChannel channel = ManagedChannelBuilder.forAddress(serverAddress, serverPort).usePlaintext().build();
        blockingStub = BillingServiceGrpc.newBlockingStub(channel);
        //now once we have created blockingStub we can use it to make grpc calls to the BillingService grpc server
    }

    public BillingResponse createBillingAccount(String patientId,String name, String email) {
        log.info("Creating billing account for patientId: {}, {}, {}", patientId, name, email);
        //build the request
        BillingRequest request = BillingRequest.newBuilder()
                .setPatientId(patientId).setName(name).setEmail(email).build();
        //make the grpc call using blockingStub
        BillingResponse response = blockingStub.createBillingAccount(request);
        log.info("Received billing account creation response: {}", response);
        return response;
    }
}
