### POST request to save a new patient
POST http://localhost:8000/api/patients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbElkIjoicml0aWsxQGV4YW1wbGUuY29tIiwiaWQiOjIsInN1YiI6InJpdGlrMSIsImlhdCI6MTc2MjY1MDI5OCwiZXhwIjoxNzYyNjUyMDk4fQ.pYt0bStKaflsz_WdlxRYe279seMYNtHSnBWSS1zuQAM

{
  "name": "Ritik",
  "email": "ritik22@gmail.com",
  "address": "Noida, UP, India",
  "dateOfBirth": "2000-06-21",
  "registeredDate": "2024-05-31"
}
###