spring.application.name=appointment-service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5006/db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

patient.service.url=${PATIENT_SERVICE_URL:http://localhost:8080}
