### POST request to example server
POST http://localhost:8000/api/auth/register-user
Content-Type: application/json

{
  "userName": "ritik1",
  "emailId": "ritik1@example.com",
  "password": "password",
  "phoneNumber": "7838165411"
}